### ISSUE TITLE
Classes which contain methods with PHP 7.1 nullable return types trigger error

### ISSUE THREAD

**Issue by lougreenwood** [hanneskod/classtools#10]
A number of my class methods have been converted to PHP 7.1 nullable return types.

https://wiki.php.net/rfc/nullable_types

It seems that any class which contains a method which implements nullable return types triggers an error and the class isn't included in the classmap.

Here's an example class which causes this bug:
```
public static function someMethod( string $some_param ) : ?string {
	return null;
}
```

This gives me an error that looks like this:
`Array ( [0] => Syntax error, unexpected '?' on line 10 in /path/to/my/class.php )`

**Comment by hanneskod** [comment]
Hi and thanx for reporting!

I have now updated php-parser to version 3 and that should add support for php 7.1.

Please reopen issue if the problem persists..

Happy new year!
