### ISSUE TITLE
License Missing

### ISSUE THREAD

**Issue by jasperf** [hanneskod/classtools#22]
Seems this package is missing a [LICENSE.md](https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository)

```
Your application has a total of 1 package(s) that you may not be legally allowed to use. By default, we assume the MIT, Apache-2.0, ISC, BSD Clause 2 & 3 and LGPL licenses to be legally valid for use for proprietary or commercial applications. However, you are free to change this in the Enlightn config. Unsafe packages include [hanneskod/classtools: WTFPL]
Documentation URL: https://www.laravel-enlightn.com/docs/security/license-analyzer.html
```

Would you mind adding one, preferably MIT like Laravel PHP?

**Comment by hanneskod** [comment]
It is actually licensed under the [WTFPL](http://www.wtfpl.net/) as stated in composer.json. You might want to add it to your list of allowed licenses.

Adding the license text in the very near future..
